### ISSUE TITLE
Does not pass a KICS Scan

### ISSUE THREAD

**Issue by balq60** [aws-samples/serverless-patterns#1105]
I pulled the code down and ran a KICS Scan against the code.

There are some things in here that should probably be fixed.

Others could be ignore, but if ignored a comment as to why would be good to document.
[kics-results.zip](https://github.com/aws-samples/serverless-patterns/files/10853872/kics-results.zip)

**Comment by jbesw** [comment]
The patterns library is intended to provide a quick starting point for developers building serverless applications. The patterns are run through a number of internal tests to ensure we balance secure implementations with practical guidance. In the same way that a code snippet from docs does not implement KMS keys, S3 bucket versioning and IAM Access Analyzer in order to convey how to use the service, we do not implement every feature available in order to keep the examples understandable and useful.

For example, in this list:
- S3 Bucket Without Enabled MFA Delete: this should be decided by the developer.
- Lambda Functions Without X-Ray Tracing: X-Ray usage should be decided by the developer.
- Name Is Not Snake Case: naming conventions should be decided by the developer.
- S3 Bucket versioning: this increases storage cost and may not be required in most projects, so should be decided by the developer.
- S3 Bucket SSE Disabled: Amazon S3 now applies server-side encryption with Amazon S3 managed keys (SSE-S3) as the base level of encryption for every bucket in Amazon S3.

If you have concerns over a specific pattern, please open one ticket per pattern so we can send to the author.
