### ISSUE TITLE
New pattern submission : s3-lambda-textract-cdktf - extracts text, handwriting, and data from scanned expense documents

### ISSUE THREAD

**Issue by iobreaker** [aws-samples/serverless-patterns#653]
The Terraform template in this pattern allows you to use Amazon Textract (a machine learning service) to automatically extracts text, handwriting, and data from scanned expense documents

The deployment is done using CDKTF

Deployed resources:

- S3 Buckets with blocked public access
- Lambda function in python
-  Lambda Layer for Pillow python library
-  Cloudwatch log group for Lambda function
-  Required roles and policies

## GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/647

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Comment by jbesw** [comment]
This is too complex for the current catalog of patterns. We may expand the feature in the future to include more complex examples. Thanks for submitting, and sorry we can't merge at this time.

**Comment by iobreaker** [comment]
Hi @jbesw 
Thanks a lot for taking time to review this new pattern.
No problem if it cannot be added to the current catalog.
Just for my understanding (for next patterns), what make this one "too complex" ? is it regarding the use of cdktf ? 
Kind Regards

**Comment by jbesw** [comment]
Generally, the patterns are 2-4 services that provide a skeleton for customers to use for their own applications. This submission provided a more complete application, incorporating more services and features like layers. It's a fine line, but I would catalog this under an application example instead of a pattern. I hope this helps and look forward to more submiissions!
